name = "prime-league-platform"
compatibility_date = "2026-07-01"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "prime-league-db"
database_id = "INSERISCI_QUI_DATABASE_ID"
